### ISSUE TITLE
Update neo4j dumps

### ISSUE THREAD

**Issue by ceefour** [opencog/test-datasets#39]
Restructure to support new generic truth value. Please update neo4j dumps from :

1. https://drive.google.com/file/d/0B9dx38a6NVxKeE11bmh3ZGpRVFk/view?usp=sharing
2. https://drive.google.com/file/d/0B9dx38a6NVxKUHN5ZmlTN2Q2YVk/view?usp=sharing

cc @AmeBel Thank you :)

**Comment by AmeBel** [comment]
How is the work progressing with regards to saving atomspace content to neo4j ? Running scripts to populate neo4j is all good but is not a priority.

**Comment by AmeBel** [comment]
can be found at http://dl.opencog.org/.  thanks
